baseURL = "http://example.org/"
languageCode = "en-us"
theme = "LoveIt"
title = "My New Hugo Site"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "pages"
    pre = ""
    post = ""
    name = "Pages"
    url = "/pages/"
    title = "pages"
