baseURL = "https://sakerhetspodcasten.se"
languageCode = "en-us"
theme = "LoveIt"
title = "Säkerhetspodcasten"

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "light"
  title = "Säkerhetspodcasten"
  description = "Säkerhetspodcasten - Sveriges första? podcast om IT-säkerhet"
  #images = ["/images/sakerhetspodcasten.png"]

  [params.home]
    [params.home.profile]
      avatarUrl = "/images/sakerhetspodcasten.png"
      subtitle = ""

  [params.header]
    [params.header.title]
      name  = "Säkerhetspodcasten"

  [params.page]
    [params.page.share]
      enable = false

  [params.footer]
    enable = false

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Pods"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "lyssna"
    pre = ""
    post = ""
    name = "Lyssna!"
    url = "/pages/lyssna"
    title = "Lyssna"
  [[menu.main]]
    weight = 3
    identifier = "kontakt"
    pre = ""
    post = ""
    name = "Kontakt"
    url = "/pages/kontakt"
    title = "kontakt"
  [[menu.main]]
    weight = 4
    identifier = "Panelen"
    pre = ""
    post = ""
    name = "Panelen"
    url = "/pages/panelen"
    title = "panelen"
  [[menu.main]]
    weight = 5
    identifier = "Supporters"
    pre = ""
    post = ""
    name = "Supporters"
    url = "/pages/supportersida-2"
    title = "supporters"
